project:
  type: website
  output-dir: docs

website:
  title: "e-makro"
  navbar:
    left:
      - href: index.qmd
        text: Materi
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

