---
title: "Deskripsi Mata Kuliah"
---

Ekonomi makro adalah sebuah cabang dari Ilmu Ekonomi yang menerapkan teori ekonomi untuk mengkaji kegiatan perekonomian secara secara keseluruhan suatu negara atau wilayah. Pembahasannya meliputi pertumbuhan, siklus dan tingkat harga ekonomi. Ekonomi makro berangkat dari fakta-fakta umum (*stylized facts*) yang terjadi di dunia nyata, kemudian membangun kerangka kerja teoritis untuk menjelaskan fakta-fakta ini.

Model-model ekonomi menggunakan tiga "bahasa" yaitu: (i) verbal, (ii) grafik, and (iii) matematik. Bahasa verbal memiliki kelebihan lebih mudah dipahami, tetapi terkadang kurang logis. Bahasa grafik menawarkan keunggulan pemahaman visual, tetapi kekurangannya grafik yang dibuat melenceng dari sifat model yang sebenarnya. Bahasa matematik lebih logis, tetapi terkadang sulit dipelajari dan dipahami.

Pada mata kuliah Pengantar Ekonomi Makro ini kita akan menggunakan tiga bahasa ini untuk mempelajari persoalan-persoalan ekonomi makro. Matakuliah ini bersifat wajib di Fakultas Ekonomi (3 SKS) terdiri dari sembilan modul:

1.  Konsep Dasar Ilmu Ekonomi.
2.  Pendapatan Nasional.
3.  Konsumsi, Tabungan dan Investasi.
4.  Permintaan Agregat dan Angka Pengganda.
5.  Uang dan Peranannya dalam Perekonomian.
6.  Peran Pemerintah dalam Perekonomian dan Kebijakan Fiskal.
7.  Penawaran Agregat dan Pertumbuhan Ekonomi.
8.  Stabilitas Harga, Pengangguran dan Siklus Bisnis.
9.  Perekonomian Terbuka.

Buku Rujukan:

1.  Harmadi, Sonny HB (2010), Pengantar Ekonomi Makro ESPA4110
2.  Baumol, William J., Alan S. Blinder, and John L. Solow (2020), Macroeconomics: Principles and Policy, Fourteenth Edition. Cengage Learning, Inc.
3.  Case, Karl E., Ray C. Fair and Sharon M. Oster, (2017). Principles of Macroeconomics. Pearson.
4.  Mishkin, Frederic S., (2015). Macroeconomics Policy and Practice. Second Edition. Pearson.
